console.log(Array.isArray([]));
console.log();
console.log(Array.isArray([1]));
console.log();
console.log(Array.isArray(null));
console.log();
console.log(Array.isArray(undefined));
console.log();
console.log(Array.isArray(17));
console.log();
console.log(Array.isArray("Array"));
console.log();
console.log(Array.isArray(true));
console.log();
console.log(Array.isArray(false));
console.log();
console.log(Array.isArray({_proto_: Array.prototype}));
console.log();
var ary="djkjdfnksj";
console.log(Array.isArray(ary));
console.log();
